module.exports = () => {
    return [{
            "id": 1,
            "idCity": 5,
            "idUser": 1,
            "name": "Appartement coquet",
            "description": "Un bel appart confortable au coeur de Marseille.",
            "rooms": 2,
            "bathrooms": 1,
            "maxGuests": 4,
            "priceByNight": 80, 
            "imageOne": "https://www.lucyinteriordesign.com/images-portfolio/scandinavian_modern/01.jpg",
            "imageTwo": "https://st.hzcdn.com/simgs/4f014a8f043d30f9_4-9430/home-design.jpg",
            "imageThree": "https://live.staticflickr.com/4470/37474524970_8a098a7385_b.jpg",
        },
        {
            "id": 2,
            "idCity": 1,
            "idUser": 1,
            "name": "Mon beau studio",
            "description": "Un petit studio dans le centre historique de Paris.",
            "rooms": 1,
            "bathrooms": 1,
            "maxGuests": 2,
            "priceByNight": 100, 
            "imageOne": "https://static.cotemaison.fr/medias_11942/w_1815,h_1362,c_crop,x_51,y_0/w_640,h_358,c_fill,g_center/v1582206789/petit-appartement-parisien-haut-en-couleur-tons-vert-et-roses_6114651.jpg",
            "imageTwo": "https://img-3.journaldesfemmes.fr/Dd1OX4O1V6297rYnthOgTfhc0tU=/819x546/smart/67f077ebcf204b92b817fd5216eca4ee/ccmcms-jdf/10782255.jpg",
            "imageThree": "https://st.hzcdn.com/simgs/48d19153042aa1be_4-7898/home-design.jpg",
        },
        {
            "id": 3,
            "idCity": 17,
            "idUser": 2,
            "name": "Milkyway",
            "description": "View on meteor all day long.",
            "rooms": 1,
            "bathrooms": 1,
            "maxGuests": 50,
            "priceByNight": 3500, 
            "imageOne": "https://www.sloft-magazine.com/wp-content/uploads/2017/12/La-vue-sur-le-salon-750x500.jpg",
            "imageTwo": "https://i.pinimg.com/originals/7b/6d/63/7b6d63f16c1845a01bef60ca0ee194bb.jpg",
            "imageThree": "https://sf2.viepratique.fr/wp-content/uploads/sites/8/2019/03/mg_0670remy-deluze_hd-615x410.jpg",
        },
        {
            "id": 4,
            "idCity": 16,
            "idUser": 4,
            "name": "Lindo habitación",
            "description": "Bel appartement refait récemment.",
            "rooms": 3,
            "bathrooms": 3,
            "maxGuests": 10,
            "priceByNight": 200, 
            "imageOne":"https://www.planete-deco.fr/wp-content/uploads/2020/04/TE0.jpg",
            "imageTwo": "https://www.amenagementdesign.com/wp-content/uploads/2016/11/deco-scandinave-cuisine.jpg",
            "imageThree": "https://fr.homenal.com/wp-content/uploads/2018/09/decoration-salle-de-bain-design-zen.jpg",
        },
        {
            "id": 5,
            "idCity": 13,
            "idUser": 3,
            "name": "Maison lumineuse",
            "description": "Intérieur lumineux et moderne, idéal pour séjourner au calme.",
            "rooms": 2,
            "bathrooms": 1,
            "maxGuests": 5,
            "priceByNight": 100, 
            "imageOne":"https://designmag.fr/wp-content/uploads/2015/12/appartement-deco-design-interieur.jpg",
            "imageTwo": "https://www.mh-deco.fr/wp-content/uploads/2015/12/Decoration-cuisine-meudon.jpg",
            "imageThree": "https://i.pinimg.com/originals/7b/00/76/7b00768087d2edd2a0d4f2218c3733ae.jpg",
        },
        {
            "id": 6,
            "idCity": 1,
            "idUser": 2,
            "name": "Studio sous les toits",
            "description": "Le charme parisien à son comble, sous les combles…",
            "rooms": 1,
            "bathrooms": 1,
            "maxGuests": 3,
            "priceByNight": 100, 
            "imageOne":"https://www.book-a-flat.com/photo/paris/9557/salon1.jpg",
            "imageTwo": "https://edito.seloger.com/sites/default/files/article/image/petite-cuisine-moderne-appartement.jpg",
            "imageThree": "https://alexispaoli.com/wp-content/uploads/2019/04/11-salle-de-bain-moderne-appartement-16e-1030x687.jpg",
        },
        {
            "id": 7,
            "idCity": 2,
            "idUser": 1,
            "name": "Appartement moderne",
            "description": "Refait à neuf et avec style, pour les amateurs de design c'est l'appartement contemporain idéal.",
            "rooms": 4,
            "bathrooms": 3,
            "maxGuests": 10,
            "priceByNight": 500, 
            "imageOne": "https://maison1.advcdn.net/images/medias/000/043/000043464/660.jpg",
            "imageTwo": "https://www.book-a-flat.com/magazine/wp-content/uploads/2018/12/deco-cuisine-appartement-paris-location-meublee-carreaux-ciment-retro-966x644.jpg",
            "imageThree": "https://www.book-a-flat.com/magazine/wp-content/uploads/2019/01/avant-apres-renovation-salle-de-bain-appartement-parisien-deco-1.jpg",
        },
        {
            "id": 8,
            "idCity": 5,
            "idUser": 5,
            "name": "Grand loft lumineux",
            "description": "Notre loft familial est très agréable à vivre, vous vous y sentirez comme chez vous.",
            "rooms": 1,
            "bathrooms": 1,
            "maxGuests": 6,
            "priceByNight": 200, 
            "imageOne": "https://resize-elle.ladmedia.fr/rcrop/638,,forcex/img/var/plain_site/storage/images/deco/news-tendances/deco-quoi-de-neuf/88511882-1-fre-FR/Deco-Quoi-de-neuf.jpg",
            "imageTwo": "https://i2.wp.com/www.planete-deco.fr/wp-content/uploads/2019/03/AB1-1.jpg?ssl=1",
            "imageThree": "https://static.cotemaison.fr/medias_10546/w_1966,h_1100,c_crop,x_0,y_184/w_640,h_360,c_fill,g_north/v1439992695/la-grande-salle-de-bains-de-l-appartement_5399847.jpg",
        },
        {
            "id": 9,
            "idCity": 5,
            "idUser": 5,
            "name": "Petit pied à terre calme",
            "description": "Ce petit appartement est confortable et ressourçant.",
            "rooms": 2 ,
            "bathrooms": 1,
            "maxGuests": 3,
            "priceByNight": 90, 
            "imageOne": "https://www.turbulences-deco.fr/wp-content/uploads/2018/02/fantastic-Frank_VASASTAN-NORRMALM_1-745x497.jpg",
            "imageTwo": "https://i0.wp.com/www.unehirondelledanslestiroirs.fr/wp-content/uploads/2016/08/appartement-cuisine-ouverte-3.jpg?fit=1050%2C700&ssl=1",
            "imageThree": "https://lh3.googleusercontent.com/proxy/sKA5o2CyeXtnzmGpjt7g7qDupnmkphBNU0tqeShCw1f-kxuI_KuVYTS3xARa3MMw8D4WClECHHMT9SUg0-Vy2qqwOn7G6R7JbXEy9M86H7g1wGZO794u58-ncTGLGaR5AbnYHnNlanUIFybEtdyfe35-IRqeg_jToHpM",
        },
        {
            "id": 10,
            "idCity": 1,
            "idUser": 1,
            "name": "Appartement convivial",
            "description": "Cocon familial idéalement situé, proche ligne de métro 3.",
            "rooms": 3,
            "bathrooms": 2,
            "maxGuests": 7,
            "priceByNight": 200, 
            "imageOne": "https://assets.afcdn.com/story/20191226/2036083_w980h638c1cx1440cy750cxt0cyt0cxb2880cyb1500.jpg",
            "imageTwo": "https://www.planete-deco.fr/wp-content/uploads/2019/01/EV1.jpg",
            "imageThree": "https://www.rci.fm/sites/default/files/2020-01/bathroom-2132342_960_720.jpg",
        },
        {
            "id": 11,
            "idCity": 1,
            "idUser": 1,
            "name": "Appartement contemporain",
            "description": "Refait à neuf il y a quelques mois, idéal pour séjourner ou abriter des réunions.",
            "rooms": 3,
            "bathrooms": 2,
            "maxGuests": 10,
            "priceByNight": 300, 
            "imageOne": "https://www.carre-habitat.com/sites/default/files/styles/image_text_paragraph/public/2019-08/cuisine-maison-minimaliste_0.jpg?itok=bHMAUO__", 
            "imageTwo": "https://static.cotemaison.fr/medias_11030/w_640,h_360,c_fill,g_north/v1488300435/petite-cuisine-en-bois-blanche_5647461.jpg",
            "imageThree": "https://st.hzcdn.com/simgs/8ce1db35042aa1c4_4-7897/home-design.jpg",
        },
        {
            "id": 12,
            "idCity": 1,
            "idUser": 2,
            "name": "Appartement minimaliste",
            "description": "Venez vivre une experience minimaliste et éco-responsable!.",
            "rooms": 1,
            "bathrooms": 1,
            "maxGuests": 4,
            "priceByNight": 110, 
            "imageOne": "https://latelier-azimute.fr/wp-content/uploads/2015/12/appartement-style-japonais-13-e1415866824494.jpg",
            "imageTwo": "https://i.pinimg.com/originals/a7/d9/07/a7d907870392d5f79aaf45ccbe02eb1f.jpg",
            "imageThree": "https://www.designferia.com/sites/default/files/styles/article_images__s640_/public/field/image/salle-de-bain-chic-appartement-design-industriel_0.jpg?itok=BPwWuN9V",
        },
    ];
};